### ISSUE TITLE
NPM Lifecycle script issue when nodeModulesDir is manual

### ISSUE THREAD

**Issue by Mikescops** [redabacha/remix-deno-vite-template#3]
Hello,

Thanks for your work here and the fast update to Deno 2.
I was trying it with a fresh project and ended it up with the following error:

```
% deno task dev
Task dev deno run -A npm:@remix-run/dev vite:dev
Warning The following packages contained npm lifecycle scripts (preinstall/install/postinstall) that were not executed:
┠─ npm:esbuild@0.17.6
┃
┠─ This may cause the packages to not work correctly.
┠─ Lifecycle scripts are only supported when using a `node_modules` directory.
┠─ Enable it in your deno config file:
┖─ "nodeModulesDir": "auto"
```

Here are the steps I did before:
```
deno run -A npm:create-remix@latest --template redabacha/remix-deno-vite-template

 remix   v2.13.1 💿 Let's build a better website...

   dir   Where should we create your new project?
         ./remix-project

      ◼  Template: Using redabacha/remix-deno-vite-template...
      ✔  Template copied

   git   Initialize a new git repository?
         Yes

  deps   Install dependencies with npm?
         No
      ◼  Skipping install step. Remember to install dependencies after setup with npm install.

      ✔  Git initialized

  done   That's it!
  ```
  
  Updating to `"nodeModulesDir": "auto",` works well but I'm not sure if manual was better in the first place. LMK.

**Comment by redabacha** [comment]
hey @Mikescops i believe that's expected when using nodeModulesDir manual as you have to run `deno install` first before running any of the tasks. however it's good that you pointed out that it also works with nodeModulesDir being set to auto, i will investigate to see if it makes sense to change the default here to use that instead - i.e. we're still using the remix versions defined the deno.json for running commands and not accidentally using different versions etc.

**Comment by Mikescops** [comment]
Alright thanks for checking, all this deno stuff is still pretty new to me so i'm trying to figure out the best practices.
