### ISSUE TITLE
Deno v2.0.6 Updates

### ISSUE THREAD

**Issue by pandapaul** [redabacha/remix-deno-vite-template#6]
Just a heads up that Deno v2.0.6 seems to provide the necessary updates to allow for using Deno alone for type checking.  🥳 

https://github.com/denoland/deno/releases/tag/v2.0.6
Specifically:  https://github.com/denoland/deno/pull/26680

Testing your branch for that (but with `"nodeModulesDir": "manual"`) went well. 👍

**Comment by redabacha** [comment]
hi @pandapaul,

thank you for bringing this up. this is awesome and unfortunately didn't have much free time to look at this sooner. i will look now to make this the default approach for this template and create a branch for the current approach instead.

**Comment by redabacha** [comment]
okay so this is done now and deno typechecking is the new default, please report any problems you may discover!

**Comment by pandapaul** [comment]
Awesome! Thanks for doing that and for providing the repo overall. Very helpful in figuring out how to get the three tools to play nicely with one another.
